import localFont from "next/font/local";
import "./globals.css";

// Load the GeistSans font
const geistSans = localFont({
  src: "./fonts/GeistVF.woff", // Check the correct path for your fonts
  variable: "--font-geist-sans",
  weight: "100 900", // Variable font weight
});

// Load the GeistMono font
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff", // Check the correct path for your fonts
  variable: "--font-geist-mono",
  weight: "100 900", // Variable font weight
});

// Metadata for the application
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout for wrapping the main app
export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
